config/routes.rb
Rails.application.routes.draw do
 root 'home#index'
 get '/login' => 'home#login'
 get '/about' => 'about#who'
 get '/logout' => 'home#logout'
 post '/Auth' => 'home#authenticate'
 get '/gallery' => 'home#gallery'
 get '/loggedin' => 'home#logged'
 get '/tripod' => 'home#tri'
 resources :messages, only: [:index,:new,:create]

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

 def who
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

 def index
 end

 def about
 end

 def login
 end

 def authenticate
  if params[:a1].casecmp("tripod")==0 && (params[:a2].casecmp("crocodile")==0 || params[:a2].casecmp("croc")==0) && params[:a3].casecmp("DPRK")==0
   session[:loggedin]=true
   flash[:success]="Logged in ! :)"
   redirect_to '/loggedin'
  else
   flash[:danger]="Incorrect"
   redirect_to '/login'
  end
 end

 def logout
  session[:loggedin]=false
  flash[:success]="Logged out"
  redirect_to root_path
 end

 def gallery
 end

 def logged
  if session[:loggedin]==false
    redirect_to root_path
  end
 end

 def tri
  if session[:loggedin]==false
    redirect_to root_path
  end
 end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

 def index
  if session[:loggedin] == false
	flash[:danger]="Access denied"
	redirect_to root_path
  end
  @messages=Message.all
 end

 def new 
  @message=Message.new
 end

 def create
  @message=Message.new(message_param)
  if @message.save 
    redirect_to root_path, alert: "Thank you ! Much appreciated !"
  else 
    redirect_to new_message_path
  end
 end

 def message_param
  params.require(:message).permit(:name,:title,:content,:image,:image_present)
 end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/about/who.html.erb
<%= stylesheet_link_tag 'homeabout' %>
<div class = "container-fluid">		
<div class="row">
				<div class="col-sm-1 col-md-2">
				</div>

				<div class="col-sm-10 col-md-8 jumbotron" style="background-color:rgba(255,0,0,0.5); height: 800px; overflow-y:auto; margin-top: 0">
				<br/>
				<div id ="home" style="font-size:18;color: white;">
				<b>Early Life</b><br/>
				Samiya Nasim was born in Salem on May 3 1995 to Mr.Muhammad Nasimuddin and Dr.Mussarat Feshan.She has an elder brother.
				She later moved to Chennai when her parents got transferred. She attended school at DAV Gopalapuram which she joined in 2001.
				She is currently pursuing her under-graduation in Computer Science and Engineering at SSN College.<br/> </div>
<hr/>
<div id="interests" style="font-size:18; color:white;">
				<b>Her Interests</b><br/>
				She is an excellent athlete and has competed at the state and national levels. She plays most sports.
				She loves reading, and is a huge Potterbuff. She is also Dramione fan girl.
				A movie buff, she can sit and watch movies for an entire day continuously without budging.
				She also loves theatre and has acted in a number of plays.
				</div>
<hr />
<div id="debate" style="font-size:18;color: white;">
				<b>Debating Skills</b><br/>
				Samiya is a debater par excellence. She has been debating right from her schools days and has won many competitions. She has participated and won in many national level debating championships in school. In college too she has won debates at a number of culturals. Debating led to MUNs in college. She has particpated in a number of them and has performed brilliantly. Her speaking skills are at a different level. Her research is impeccable.
</div>
<hr/>
<div id="accomplish" style="font-size:18;color:white;">
				<b>Accomplishments</b><br/>
				Her accomplishments are many. Some of them are:
			<ul><li>Won the silver medal in long jump in CBSE Nationals</li>
			<li>Ranked among the top five individual speakers in the Indian schools Debating Championship</li>
			<li>shortlisted for tryouts to represent Team India at the World Schools Debating Championship</li>
			<li>Won the SSN Best Speaker Contest</li>
			<li>Part of Lights Out Please (LOP) and acted in various plays in diverse roles </li>
			<li>Part of the college tennis team winning a number of tournaments</li>
</ul>
<hr/>
</div>
<div id="future" style="font-size:18;color:white;" >
				<b>What lies ahead</b><br/>
				Samiya sees herself pursuing her higher studies in a reputed university abroad. Followed by a short stint abroad and coming back home. Hopefully a start up back home a few years down the line. She also plans to serve society in all possible ways through her work.
</div>
				</div>

				</div>

				<div class="col-sm-1 col-md-2">
				</div>
			</div>
					<a class='button ctrl' href='#' tabindex='1' title="expand" style="background-color:rgb(0,255,0)"><span class="glyphicon glyphicon-plus"></span></a>
					<ul class='tip ctrl'>
						<li class='slice' title="Early Life"><a href='#home'><span class="glyphicon glyphicon-home" ></span></a></li>
						<li class='slice' title="Her Interests"><a href='#interests'><span class="glyphicon glyphicon-heart-empty"></span></a></li>
						<li class='slice' title="Debating Skills"><a href='#debate'><span class="glyphicon glyphicon-volume-up"></span></a></li>
						<li class='slice' title="Accomplishments"><a href='#accomplish'><span class="glyphicon glyphicon-briefcase"></span></a></li>
						<li class='slice' title="Future Life"><a href='#future'><span class="glyphicon glyphicon-globe"></span></a></li>
					</ul>


		</div>

		

app/views/home/gallery.html.erb
<%= stylesheet_link_tag 'homeindex' %>
<div class="row">
<div class="col-sm-1 col-md-2">
</div>
<div class="row">
	<div class="col-sm-10 col-md-8" style="background:url(<%= image_path 'pikachu.jpg' %>) no-repeat">
		<br/><br/><br/>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	    <li data-target="#myCarousel" data-slide-to="1"></li>
	    <li data-target="#myCarousel" data-slide-to="2"></li>
	    <li data-target="#myCarousel" data-slide-to="3"></li>
	    <li data-target="#myCarousel" data-slide-to="4"></li>
	    <li data-target="#myCarousel" data-slide-to="5"></li>
	    <li data-target="#myCarousel" data-slide-to="6"></li>
	  </ol>
	  <!-- Wrapper for slides -->
	  <div class="carousel-inner" role="listbox">
	    <div class="item active">
		<center>
	      <img src="<%= image_path 'samiya_baby.jpg' %>" height="750" width="750"/ >
		</center>
	    </div>

	    <div class="item">
		<center>
	      <img src="<%= image_path 'samiya_hbd.jpg' %>" height="750" width="750"/>
		</center>
	    </div>
	    <div class="item">
		<center>
	      <img src="<%= image_path 'samiya_quoet.jpg' %>" height="750" width="750"/ >
		</center>
	    </div>
	    <div class="item">
		<center>
	      <img src="<%= image_path 'sam_champ_new.jpg' %>" height="750" width="300"/ >
		</center>
	    </div>
	    <div class="item">
		<center>
	      <img src="<%= image_path 'samiya_saree.jpg' %>" height="750" width="300"/ >
		</center>
	    </div>
	    <div class="item">
		<center>
	      <img src="<%= image_path 'samiya_act.jpg' %>" height="750" width="750"/>
		</center>
	    </div>

	    <div class="item">
		<center>
	      <img src="<%= image_path 'samiya.jpg' %>" height="750" width="750"/ >
		</center>
	    </div>
 	 </div>

	  <!-- Left and right controls -->
	  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div><!-- carousel -->
</div><!-- second columns -->
<div class="row">
<div class="col-sm-1 col-md-2">
</div>
</div>

app/views/home/index.html.erb
<%= stylesheet_link_tag 'homeindex' %>
<div class = container-fluid>
<div class="row">
	<div class="col-sm-1 col-md-3">
	</div>
	<div class="col-sm-10 col-md-6 jumbotron" style="background-color:#996633;">
	
	<center>
		<h1>Happy Birthday Samiya !!</h1>
		<div class="well " height="350" width="350" style=" background: -webkit-radial-gradient(rgb(255, 153, 0),rgb(255, 204, 0),rgb(255,255,0)); /* Safari 5.1 to 6.0 */
									    background: -o-radial-gradient(rgb(255, 153, 0),rgb(255, 204, 0),rgb(255,255,0)); /* For Opera 11.6 to 12.0 */
									    background: -moz-radial-gradient(rgb(255, 153, 0),rgb(255, 204, 0),rgb(255,255,0)); /* For Firefox 3.6 to 15 */
									    background: radial-gradient(rgb(255, 153, 0),rgb(255, 204, 0),rgb(255,255,0)); /* Standard syntax (must be last) */">
		<img src="<%= image_path 'samiya_baby.jpg' %>" class="img-circle" alt="Cinque Terre" width="250" height="250">
		<br/><br/>
		</div><!-- well -->
		<p>On this day a star was born<br/> Read on to know more about her  <br/>
		Or Convey your wishes !</p>
	</center>
	</div><!-- second column -->

		<div class="col-sm-1 col-md-3">

		</div><!-- third column -->

</div><!-- row -->
</div>

app/views/home/logged.html.erb
<%= stylesheet_link_tag 'homeindex' %>
<div class = container-fluid>
<div class="row">
	<div class="col-sm-1 col-md-3">
	</div>
	<div class="col-sm-10 col-md-6 jumbotron" style="background-color:#996633; height: 700px; overflow-y:auto;">
	
	<center>
		<h1>Happy Birthday Samiya !!</h1>
		<div class="well " height="350" width="350" style=" background: -webkit-radial-gradient(rgb(255, 153, 0),rgb(255, 204, 0),rgb(255,255,0)); /* Safari 5.1 to 6.0 */
									    background: -o-radial-gradient(rgb(255, 153, 0),rgb(255, 204, 0),rgb(255,255,0)); /* For Opera 11.6 to 12.0 */
									    background: -moz-radial-gradient(rgb(255, 153, 0),rgb(255, 204, 0),rgb(255,255,0)); /* For Firefox 3.6 to 15 */
									    background: radial-gradient(rgb(255, 153, 0),rgb(255, 204, 0),rgb(255,255,0)); /* Standard syntax (must be last) */">
		<img src="<%= image_path 'samiya_baby.jpg' %>" class="img-circle" alt="Cinque Terre" width="250" height="250">
		<br/><br/>
		<div class="btn-group btn-group-sm">
				<button type="button" class="btn btn-primary">
   				<span class="glyphicon glyphicon-thumbs-up"></span>Like <span class="badge">5</span>
 				</button>
							
		</div>
		</div><!-- well -->
		<p>In august 2012, 3 people walked into SSN College of Engineering, with a few dreams and no expectations, clueless about what fate had in store for them. As a result of a happy accident, they got this.</p><br>
		<img src="<%= image_path 'tripod.jpg' %>" class="img-circle" alt="Cinque Terre" width="250" height="250">
		<br/><br/>
		<p>Then we eventually found out that you are more than just another friend. You are the best friend we have ever had, and can ever hope to get. We also discovered you are an angel.</p><br/>
		<img src="<%= image_path 'samiya_white.jpg' %>" class="img-circle" alt="Cinque Terre" width="250" height="250">
		<br/><br/>
		<p>Today we would like to thank the lucky stars that gave you to this world. For giving us a special friend like no other.</p>
<br/>
		</center>
	</div><!-- second column -->

		<div class="col-sm-1 col-md-3">

		</div><!-- third column -->

</div><!-- row -->
</div>

app/views/home/login.html.erb
<!--Welcome Page -->
		<div id="welcome" class="panel">
			<div class = "level2">
				<h2>Welcome</h2>
				<p>Well, only Samiya is permitted to access
				   to access certain sections of this website.
				   So to prove that you are indeed Samiya,
				   bear with us and answer a few questions , will you?
				
				They should be a breeze...
				If you are who you claim to be	</p>
				<p>
				<a href="index.html" style="color:white"> Take me back </a>
				</p>
			</div>
			<!-- ... -->
		</div>
		<!-- /welcome -->
		<%= form_tag 'Auth',id:'form' do %>
		<!-- level1 -->
		<div id="level1" class="panel">
			<div class="level2">
				<h2>Level1</h2>
				<p>Question 1</p><br/>
				<p>The three that matter most, what are they called ?<br>Of whom thy art an integral part<br>
<input type="text" name="a1" />
<br>
</p>
				 <div class="progress">
						  <div class="progress-bar progress-bar-striped active" role="progressbar"
						  aria-valuenow="1" aria-valuemin="0" aria-valuemax="3" style="width:33.3%">
						    1/3
						  </div>
					</div>

				<!-- ... -->
			</div>
		</div>
		<!-- /level1 -->

		<!-- About -->
		<div id="about" class="panel">
			<div class="level2">
				<h2>Level2</h2>
				<p>Question 2</p><br/>
				<p>Which reptile does this site celebrate ? <br>
<input type="text" name="a2" />
<br>
</p>
				 <div class="progress">
						  <div class="progress-bar progress-bar-striped active" role="progressbar"
						  aria-valuenow="2" aria-valuemin="0" aria-valuemax="3" style="width:66.6%">
						    2/3
						  </div>
					</div>
				<!-- ... -->
			</div>
		</div>
		<!-- /About -->

		<!-- level3 -->
		<div id="level3" class="panel">
			<div class="level2">
				<h2>Level3</h2>
				<p>Question 3</p><br/>
				<p>Which country does this site celebrate ? (In 4 letters)<br>
<input type="text" name="a3" />
<br>
<input type="submit" class="btn btn-primary" value="Try Me"/></p>
				 <div class="progress">
						  <div class="progress-bar progress-bar-striped active" role="progressbar"
						  aria-valuenow="3" aria-valuemin="0" aria-valuemax="3" style="width:100%">
						    3/3
						  </div>
					</div>
				<!-- ... -->
			</div>
		</div>
		<!-- /level3 -->
		<% end %>
		<!-- Header with Navigation -->
		<div id="header">
			<h1> Are you who you claim to be?</h1>
			<ul id="navigation">
				<li><a id="link-welcome" href="#welcome" onclick="change(this)" >Welcome</a></li>
				<li><a id="link-level1" href="#level1" onclick="change(this)">Level1</a></li>
				<li><a id="link-about" href="#about" onclick="change(this)">Level 2</a></li>
				<li><a id="link-level3" href="#level3" onclick="change(this)">Level3</a></li>
			</ul>

		</div>

<script type="text/javascript" >
function change(e)
{
$('#header #navigation a').css("background","rgba(0,0,0,0.3)");
e.style.background="#000";
e.style.color="#fff";
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
		
	<div class="navbar-header">
		<%if !session[:loggedin] %>
		<%= link_to 'Home',root_path, class:"navbar-brand" %>
		<% else %>
		<%= link_to 'Home','/loggedin', class:"navbar-brand" %>
		<% end %>
	</div>
	<div>
<% if session[:loggedin]==true %>
	<ul class="nav navbar-nav">
	<li><a href="/tripod">Tripod Forever</a></li>
	</ul>
<%end %>
	 <ul class="nav navbar-nav">
		<% if !session[:loggedin] %><li><%= link_to 'Who is Samiya ?' , '/about' %></li><% end %>
		<li><%= link_to 'Photo Gallery','/gallery' %></li>  
	</ul>
	<ul class="nav navbar-nav navbar-right">
<% if !session[:loggedin] %>
		<%= link_to new_message_path do %>
		<div class ="btn-group" style="right:7px;top:7px">
		<button type="button-lg" class="btn btn-primary">
		<span class="glyphicon glyphicon-envelope"></span> Message Samiya
 		</button>
		<% end %>
		<%= link_to '/login' do %>						
		<button type="button-lg" class="btn btn-primary">
		<span class="glyphicon glyphicon-log-in"></span> Log In as Samiya
 		</button>
		<% end %>
<% else %>
		<%= link_to messages_path do %>
		<div class ="btn-group" style="right:7px;top:7px">
		<button type="button-lg" class="btn btn-primary">
		<span class="glyphicon glyphicon-envelope"></span> See messages
 		</button>
		<% end %>
		<%= link_to 'logout' do %>						
		<button type="button-lg" class="btn btn-primary">
		<span class="glyphicon glyphicon-log-out"></span> Log out
 		</button>
		<% end %>
<% end %>
	</ul>
	</div>
		 	 
</nav>

<% flash.each do |key,value| %>
 <div class="alert alert-<%= key %>"><%= value %> </div>
<% end %>
<%= yield %>

<!-- container-fluid -->

</body>
</html>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
<div class="panel" id="<%=message.id %>">
<div class="level2">
<h2>With all the love</h2>
<p>
Name : <%= message.name %><br>
Title : <%= message.title %> <br>
What they say : <%= message.content %>
</p>
<br>

</div>
</div>
<% end %>

<div id="header">
<h1> Whos got stuff to say</h1>
<ul id="navigation">
<% @messages.each do |message| %>
<li><a href="#<%= message.id %>" onclick="change(this)"><%= message.name %></a></li>
<% end %>
</ul>

</div>


<script type="text/javascript" >
function change(e)
{
$('#header #navigation a').css("background","rgba(0,0,0,0.3)");
e.style.background="#000";
e.style.color="#fff";
}
</script>

app/views/messages/new.html.erb
		<!--Welcome Page -->
		<div id="welcome" class="panel">
			<div class = "level2">
				<h2>Welcome</h2>
				<p>So if you are wondering as 
				to what this is all about , its just a 
				way to let Samiya know how much you
				mean to her . The messages and the images
				that you upload can only be viwed by Samiya
				. So pour out your feelings and upload the most memorable pic
				you have with her :)	</p><br/>

			</div>
			<!-- ... -->
		</div>
		<!-- /welcome -->

<%= form_for @message do |f| %>
<div id="form1" class="panel">
<div class="level2">

<h2 style="font-size: 55px;">Say what you wanna say, on this special day</h2>
<p>Leave behind a birthday message</p>
<br>
<p>
<span class="rowf">
<span class="labelf"><%= f.label :name %></span>
<span class="formw"><%= f.text_field :name %></span>
</span>
<br>
<span class="rowf">
<span class="labelf"><%= f.label :title, 'Known as' %> </span>
<span class="formw"><%= f.text_field :title %></span>
</span>
<br>
<br>
<br>
<span class="rowf">
<%= f.label :content,class: "labelf" %>
<%= f.text_area :content,class: "formw" %>
</span>
<br>

</p>

</div>
</div >

<div id="form2" class="panel">
<div class="level2">
<h2>Got a special picture ? </h2>
<p>
<span class="row">
<span>Do you want to upload an image ?</span> <span><%= f.check_box :image_present %> </span>
</span>
<br><br>
<span class="row">
<span >Select an image: </span> <span><%= f.file_field :image %></span><br>
</span>
</p>
</div>
</div>

<div id="done" class="panel">
<div class="level2">
<h2>You are done !</h2>
<p>Thank you for taking the time. If you are done, go ahead !<br>
<%= f.submit "Send",class:"btn btn-primary" %>
</p>

</div>
</div>

<% end %>

<div id="header">
<h1> What you gotta say</h1>
<ul id="navigation">
	<li><a id="link-welcome" href="#welcome" onclick="change(this)">Welcome</a></li>
	<li><a id="link-form1" href="#form1" onclick="change(this)" >Put in your message</a></li>
	<li><a id="link-form2" href="#form2" onclick="change(this)" >Image</a></li>
	<li><a id="link-done" href="#done" onclick="change(this)" >Done</a></li>
</ul>
</div>

<script type="text/javascript" >
function change(e)
{
$('#header #navigation a').css("background","rgba(0,0,0,0.3)");
e.style.background="#000";
e.style.color="#fff";
}
</script>